version: '3.9'

services:
  app:
    container_name: be
    restart: unless-stopped
    env_file: .env
    build:
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    tty: true
    stdin_open: true
    depends_on:
      - postgres
    networks:
      - squarely

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - squarely

volumes:
  postgres:

networks:
  squarely:
